# Generated by Django 5.1.1 on 2024-09-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('resume', models.CharField(max_length=100)),
                ('Contenu', models.TextField(blank=True)),
                ('date_edition', models.DateTimeField()),
            ],
        ),
    ]
