# Generated by Django 5.1.1 on 2024-10-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_contenu_article_contenu_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='prenom',
        ),
    ]
