# Generated by Django 5.1.1 on 2024-10-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
