# Generated by Django 5.1.1 on 2024-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_userprofile_nom_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adresse_rue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
